site_name: idyllm modular
site_author: idyllm
site_url: https://idyllm.github.io
repo_url: https://github.com/idyllm/idyllm.github.io

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
  font:
    text: Radio Canada
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: 
        icon: bootstrap-icons-1.13.1/toggle-off
        name: Switch to dark mode
      primary: black
      accent: grey 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: 
        icon: bootstrap-icons-1.13.1/toggle-on
        name: Switch to light mode
      primary: blue grey
      accent: indigo
  icon:
    logo: bootstrap-icons-1.13.1/boombox

plugins:
  - search
  - include-markdown
  - mkdocs-jupyter
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories: false
      pagination_per_page: 5
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          short: true
          case: lower
  - meta
  - tags
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

markdown_extensions: 
  - pymdownx.arithmatex
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options: 
        custom_icons:
          - overrides/.icons

nav:
  - Home: 
    - blog/index.md
  - Projects: 
    - projects/index.md
    - Output:
      - projects/output/index.md
      - Design: projects/output/theory.md
      - Assembly: projects/output/assembly.md
      - Schematic: projects/output/assets/schematic.pdf
      - Source: https://github.com/xdylanm/modular-output
    - Mixer+:
      - projects/mixer/index.md
      - Design: projects/mixer/theory.md
      - Assembly: projects/mixer/assembly.md
      - Schematic: projects/mixer/assets/schematic.pdf
      - Source: https://github.com/xdylanm/modular-mixer
    - Dual VCA:
      - projects/dual-vca/index.md
      - Design: 
        - projects/dual-vca/theory.md
        - Notebook: projects/dual-vca/assets/design_calc.ipynb
      - Assembly: projects/dual-vca/assembly.md
      - Schematic: projects/dual-vca/assets/schematic.pdf
      - Source: https://github.com/xdylanm/vca-module
    - Dual Gate Delay:
      - projects/gate-delay/index.md
      - Design: 
        - projects/gate-delay/theory.md
        - IC Gate Delay: projects/gate-delay/design/ic_gate_delay.md
        - Analog Gate Delay: projects/gate-delay/design/gate_delay_theory.md
        - Gate Delay Calculation: projects/gate-delay/design/gate_delay_calc.ipynb
      - Assembly: projects/gate-delay/assembly.md
      - Schematic: projects/gate-delay/assets/schematic.pdf
      - Source: https://github.com/xdylanm/gate-delay
  - References:
    - references/index.md
    - Building Blocks:
      - references/buildingblocks/index.md
      - Linear to Exponential Converters:
        - references/buildingblocks/lin2exp.md
        - Notebook: references/buildingblocks/ptc_equiv_calc.ipynb
  - About:
    - about.md
  - Tags: tags.md
  
extra_javascript:
  - scripts/arithmatex-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/idyllm

exclude_docs: |
  **/assets/*.md

copyright: Copyright &copy; 2025 idyllm